/* ===========================================================================
   NovaPay V6.0 — 免责声明（六语完整版）
   对应文件：Desktop/免责声明文字.txt
   说明：源文件对法语/德语/意大利语的重音字符存在编码损坏（显示为 ?），
   此处按原意重新校订为地道、完整的六语文本。
   商标法声明见 icons.js 顶部。
   =========================================================================== */
const DISCLAIMERS = {
  'zh-CN': [
    { h: '1. 平台性质', p: '本网站（以下简称“本平台”）为金融模拟教育工具，旨在提供虚拟环境下的金融操作体验。本平台不提供任何真实金融服务，包括但不限于资金存储、转账、支付、投资理财、信用评估等。本平台所展示的全部交易记录、账户余额、资产变动及收益数据，均为模拟生成，不构成真实财务信息，不具备任何法律效力。严禁用户将本平台内容用于真实金融决策或作为投资依据。' },
    { h: '2. 知识产权与商标', p: '本平台界面中展示的银行卡样式、支付机构标识（含 Visa、Mastercard、American Express 等）、金融机构名称及徽标，均为其各自所有者的注册商标或商业标识。本平台仅为模拟真实使用场景、提升用户视觉体验之目的引用上述标识。本平台与上述商标所有者不存在任何合作、赞助、授权或关联关系。本平台不主张对上述商标的任何权利。用户不得将本平台内容误认为真实金融机构官方产品。未经授权使用上述商标可能构成侵权，用户应自行承担相应法律责任。' },
    { h: '3. 数据与隐私', p: '本平台运行中可能记录用户操作数据（如模拟交易记录、账户设置等），该等数据仅存储于用户本地设备或用户指定的云存储中。本平台开发者不主动收集、上传、分析或向第三方传输用户个人信息。用户应自行负责其数据存储安全。本平台不涉及收集用户真实姓名、身份证件号码、银行卡号、生物识别信息等敏感个人信息。如本平台嵌入的第三方服务涉及用户信息传输，用户应仔细阅读相关服务的隐私政策，本平台不对第三方服务的隐私保护行为承担责任。' },
    { h: '4. 责任限制与免责', p: '因平台故障、软件错误、数据模拟偏差、网络中断、第三方服务异常等原因导致的任何损失（包括但不限于时间损失、机会损失、数据丢失、心理预期落差、商业机会损失等），本平台开发者不承担任何赔偿责任。本平台按“现状”及“现有”基础提供，开发者不承诺平台无缺陷、运行不间断、数据完全准确或适用于任何特定用途。用户应自行独立判断本平台模拟结果的合理性和可靠性，严禁将模拟结果用于真实金融交易、投资决策、财务规划或其他具有法律效力的场合。' },
    { h: '5. 用户义务与使用限制', p: '用户同意严格遵守以下义务：1. 不得利用本平台进行任何违反《中华人民共和国民法典》《中华人民共和国网络安全法》《中华人民共和国个人信息保护法》及中华人民共和国其他法律法规、国际公约或公序良俗的行为；2. 不得将本平台用于真实资金交易、洗钱、欺诈、非法集资或其他非法金融活动；3. 不得反向工程、反编译、破解或以任何技术手段获取本平台源代码或核心逻辑；4. 不得将本平台或其任何部分（含界面设计、代码、模拟数据、文字内容）用于商业目的，包括但不限于出售、租赁、许可、植入广告、捆绑销售等；5. 不得通过本平台传播恶意软件、病毒、木马程序或其他有害代码；6. 发现本平台存在安全漏洞或功能异常，应及时通过指定渠道反馈，不得恶意利用或公开扩散；7. 用户对其在本平台上的所有操作行为承担全部法律责任。' },
    { h: '6. 法律适用与争议解决', p: '本免责声明及本平台的使用、解释、效力、履行及争议解决，均适用《中华人民共和国民法典》及相关中华人民共和国法律，排除冲突法规则之适用。因本平台引起的或与本平台有关的任何争议，双方应首先友好协商解决；协商不成的，任何一方有权将争议提交至开发者所在地有管辖权的人民法院诉讼解决。用户明确知晓并同意，前述争议解决条款不因用户所在国家或地区的法律规定而改变。' },
    { h: '7. 用户确认', p: '用户首次访问或使用本平台，即视为已阅读、理解并无条件同意本免责声明全部条款。如不同意本免责声明任何部分，应立即停止使用并关闭页面。本平台保留随时修订本免责声明的权利，修订版本将在本页面公布并自公布之日起生效。用户应定期查阅更新，继续使用即视为接受修订后全部内容。' },
  ],
  'zh-TW': [
    { h: '1. 平台性質', p: '本網站（以下簡稱「本平台」）為金融模擬教育工具，旨在提供虛擬環境下之金融操作體驗。本平台不提供任何真實金融服務，包括但不限於資金存儲、轉帳、支付、投資理財、信用評估等。本平台所展示之全部交易記錄、帳戶餘額、資產變動及收益數據，均為模擬生成，不構成真實財務信息，不具備任何法律效力。嚴禁用戶將本平台內容用於真實金融決策或作為投資依據。' },
    { h: '2. 知識產權與商標', p: '本平台界面中展示之銀行卡樣式、支付機構標識（含 Visa、Mastercard、銀聯、American Express 等）、金融機構名稱及徽標，均為其各自所有者之註冊商標或商業標識。本平台僅為模擬真實使用場景、提升用戶視覺體驗之目的引用上述標識。本平台與上述商標所有者不存在任何合作、贊助、授權或關聯關係。本平台不主張對上述商標之任何權利。用戶不得將本平台內容誤認為真實金融機構官方產品。未經授權使用上述標識可能構成侵權，用戶應自行承擔相應法律責任。' },
    { h: '3. 數據與隱私', p: '本平台運行中可能記錄用戶操作數據（如模擬交易記錄、帳戶設置等），該等數據僅存儲於用戶本地設備或用戶指定之雲存儲中。本平台開發者不主動收集、上傳、分析或向第三方傳輸用戶個人信息。用戶應自行負責其數據存儲安全。本平台不涉及收集用戶真實姓名、身份證件號碼、銀行卡號、生物識別信息等敏感個人信息。如本平台嵌入之第三方服務涉及用戶信息傳輸，用戶應仔細閱讀相關服務之隱私政策，本平台不對第三方服務之隱私保護行為承擔責任。' },
    { h: '4. 責任限制與免責', p: '因平台故障、軟件錯誤、數據模擬偏差、網絡中斷、第三方服務異常等原因導致之任何損失（包括但不限於時間損失、機會損失、數據丟失、心理預期落差、商業機會損失等），本平台開發者不承擔任何賠償責任。本平台按「現狀」及「現有」基礎提供，開發者不承諾平台無缺陷、運行不間斷、數據完全準確或適用於任何特定用途。用戶應自行獨立判斷本平台模擬結果之合理性和可靠性，嚴禁將模擬結果用於真實金融交易、投資決策、財務規劃或其他具有法律效力之場合。' },
    { h: '5. 用戶義務與使用限制', p: '用戶同意嚴格遵守以下義務：1. 不得利用本平台進行任何違反中華人民共和國法律法規及相關法律、國際公約或公序良俗之行為；2. 不得將本平台用於真實資金交易、洗錢、欺詐、非法集資或其他非法金融活動；3. 不得反向工程、反編譯、破解或以任何技術手段獲取本平台源代碼或核心邏輯；4. 不得將本平台或其任何部分（含界面設計、代碼、模擬數據、文字內容）用於商業目的，包括但不限於出售、租賃、許可、植入廣告、捆綁銷售等；5. 不得通過本平台傳播惡意軟件、病毒、木馬程序或其他有害代碼；6. 發現本平台存在安全漏洞或功能異常，應及時通過指定渠道反饋，不得惡意利用或公開擴散；7. 用戶對其在本平台上之所有操作行為承擔全部法律責任。' },
    { h: '6. 法律適用與爭議解決', p: '本免責聲明及本平台之使用、解釋、效力、履行及爭議解決，均適用中華人民共和國法律。因本平台引起之或與本平台有關之任何爭議，雙方應首先友好協商解決；協商不成者，任何一方有權將爭議提交至有管轄權之法院訴訟解決。用戶明確知悉並同意，前述爭議解決條款不因用戶所在國家或地區之法律規定而改變。' },
    { h: '7. 用戶確認', p: '用戶首次訪問或使用本平台，即視為已閱讀、理解並無條件同意本免責聲明全部條款。如不同意本免責聲明任何部分，應立即停止使用並關閉頁面。本平台保留隨時修訂本免責聲明之權利，修訂版本將在本頁面公佈並自公佈之日起生效。用戶應定期查閱更新，繼續使用即視為接受修訂後全部內容。' },
  ],
  'en': [
    { h: '1. Nature of the Platform', p: 'This website (hereinafter referred to as the "Platform") is a financial simulation educational tool designed to provide a virtual environment for financial operation experiences. The Platform does not provide any real financial services, including but not limited to fund custody, money transfers, payments, investment management, or credit assessment. All transaction records, account balances, asset fluctuations, and yield data displayed on the Platform are simulated and generated for demonstration purposes only. Such data does not constitute real financial information and carries no legal validity. Users are strictly prohibited from using any Platform content for real-world financial decision-making or as a basis for investment.' },
    { h: '2. Intellectual Property and Trademarks', p: 'The credit card designs, payment institution logos (including but not limited to Visa, Mastercard, American Express, etc.), financial institution names, and emblems displayed on the Platform interface are registered trademarks or commercial identifiers of their respective owners. The Platform references the above marks solely for the purpose of simulating realistic usage scenarios and enhancing the user visual experience. The Platform has no cooperation, sponsorship, authorization, or affiliation with the aforementioned trademark owners. The Platform does not claim any rights to the above trademarks. Users shall not misinterpret any Platform content as an official product of any real financial institution. Unauthorised use of the above trademarks may constitute infringement, and users shall bear corresponding legal liability.' },
    { h: '3. Data and Privacy', p: 'During Platform operation, user activity data (such as simulated transaction records and account settings) may be recorded. Such data is stored solely on the user’s local device or within the user’s designated cloud storage. The Platform developer does not actively collect, upload, analyse, or transmit users’ personal information to third parties. Users are solely responsible for the security of their data storage. The Platform does not involve the collection of sensitive personal information, including but not limited to users’ real names, national identification numbers, bank card details, or biometric data. Where third-party services embedded in the Platform involve the transmission of user information, users should carefully read the privacy policies of such services, and the Platform assumes no responsibility for the privacy protection practices of third-party services.' },
    { h: '4. Limitation of Liability and Disclaimer', p: 'The Platform developer shall not bear any liability for compensation of any kind arising from platform malfunctions, software errors, data simulation inaccuracies, network interruptions, third-party service anomalies, or any other causes, including but not limited to loss of time, loss of opportunity, data loss, disappointment in performance or outcomes, or loss of business opportunities. The Platform is provided on an "as is" and "as available" basis. The developer does not warrant that the Platform is error-free, uninterrupted, entirely accurate, or suitable for any particular purpose. Users shall independently assess the reasonableness and reliability of the Platform’s simulation results and are strictly prohibited from applying such results to real financial transactions, investment decisions, financial planning, or any other legally binding contexts.' },
    { h: '5. User Obligations and Usage Restrictions', p: 'Users agree to strictly comply with the following obligations: 1. Not to use the Platform for any activity that violates applicable laws and regulations, international conventions, or public order and good morals; 2. Not to use the Platform for real money transactions, money laundering, fraud, illegal fundraising, or other illegal financial activities; 3. Not to reverse engineer, decompile, crack, or employ any technical means to obtain the Platform’s source code or core logic; 4. Not to use the Platform, or any part thereof (including interface designs, code, simulated data, and textual content), for commercial purposes, including but not limited to sale, lease, licensing, advertising embedding, or bundling; 5. Not to transmit or disseminate any malicious software, viruses, Trojan horses, or other harmful code through the Platform; 6. To promptly report any security vulnerabilities or functional anomalies through designated channels, and not to exploit or publicly disclose such findings maliciously; 7. To bear full legal responsibility for all actions performed on the Platform.' },
    { h: '6. Governing Law and Dispute Resolution', p: 'This Disclaimer, together with the use, interpretation, validity, performance, and dispute resolution of the Platform, shall be governed by and construed in accordance with the laws of the jurisdiction in which the developer is established, excluding its conflict of law rules. Any dispute arising out of or relating to the Platform shall first be submitted to friendly negotiation between the parties. In the event that negotiation fails, either party has the right to submit the dispute to the competent courts of that jurisdiction for litigation. Users expressly acknowledge and agree that the foregoing dispute resolution clause shall not be altered by the legal provisions of the user’s country or region of residence.' },
    { h: '7. User Acknowledgment', p: 'By accessing or using the Platform for the first time, users are deemed to have read, understood, and unconditionally accepted all terms of this Disclaimer. If a user does not agree to any part of this Disclaimer, they shall immediately cease using the Platform and close the relevant page. The Platform reserves the right to revise this Disclaimer at any time, with the revised version to be published on this page and effective as of the date of publication. Users are obligated to periodically review updates, and continued use of the Platform shall constitute acceptance of all revised terms.' },
  ],
  'it': [
    { h: '1. Natura della Piattaforma', p: 'Il presente sito web (di seguito denominato la "Piattaforma") è uno strumento educativo di simulazione finanziaria progettato per offrire un ambiente virtuale per esperienze operative finanziarie. La Piattaforma non fornisce alcun servizio finanziario reale, inclusi ma non limitati a custodia di fondi, trasferimenti di denaro, pagamenti, gestione degli investimenti o valutazione del credito. Tutti i registri delle transazioni, i saldi dei conti, le fluttuazioni patrimoniali e i dati sui rendimenti visualizzati sulla Piattaforma sono generati in modo simulato esclusivamente a scopo dimostrativo. Tali dati non costituiscono informazioni finanziarie reali e non hanno alcuna validità legale. È severamente vietato agli utenti utilizzare qualsiasi contenuto della Piattaforma per decisioni finanziarie nel mondo reale o come base per investimenti.' },
    { h: '2. Proprietà Intellettuale e Marchi', p: 'I design delle carte di credito, i loghi degli istituti di pagamento (inclusi ma non limitati a Visa, Mastercard, American Express, ecc.), i nomi delle istituzioni finanziarie e gli emblemi visualizzati sull’interfaccia della Piattaforma sono marchi registrati o identificatori commerciali dei rispettivi proprietari. La Piattaforma fa riferimento ai suddetti marchi esclusivamente allo scopo di simulare scenari di utilizzo realistici e migliorare l’esperienza visiva dell’utente. La Piattaforma non ha alcuna cooperazione, sponsorizzazione, autorizzazione o affiliazione con i suddetti proprietari di marchi. La Piattaforma non rivendica alcun diritto sui suddetti marchi. Gli utenti non devono interpretare erroneamente alcun contenuto della Piattaforma come prodotto ufficiale di qualsiasi istituzione finanziaria reale. L’uso non autorizzato dei suddetti marchi può costituire violazione e gli utenti si assumono la corrispondente responsabilità legale.' },
    { h: '3. Dati e Privacy', p: 'Durante il funzionamento della Piattaforma, possono essere registrati dati relativi alle attività degli utenti (come registri di transazioni simulate e impostazioni dei conti). Tali dati sono memorizzati esclusivamente sul dispositivo locale dell’utente o nell’archivio cloud designato dall’utente. Lo sviluppatore della Piattaforma non raccoglie, carica, analizza né trasmette attivamente i dati personali degli utenti a terzi. Gli utenti sono gli unici responsabili della sicurezza del proprio archivio dati. La Piattaforma non comporta la raccolta di informazioni personali sensibili, inclusi ma non limitati a nomi reali, numeri di identificazione nazionali, dettagli di carte bancarie o dati biometrici. Laddove servizi di terze parti integrati nella Piattaforma comportino la trasmissione di informazioni degli utenti, questi sono invitati a leggere attentamente le politiche sulla privacy di tali servizi, e la Piattaforma non si assume alcuna responsabilità per le pratiche di protezione della privacy di servizi terzi.' },
    { h: '4. Limitazione di Responsabilità ed Esclusione di Garanzia', p: 'Lo sviluppatore della Piattaforma non si assume alcuna responsabilità per danni di qualsiasi natura derivanti da malfunzionamenti della piattaforma, errori software, inesattezze nella simulazione dei dati, interruzioni di rete, anomalie di servizi terzi o qualsiasi altra causa, inclusi ma non limitati a perdita di tempo, perdita di opportunità, perdita di dati, delusione per le prestazioni o i risultati, o perdita di opportunità commerciali. La Piattaforma è fornita "così com’è" e "come disponibile". Lo sviluppatore non garantisce che la Piattaforma sia priva di errori, ininterrotta, completamente accurata o adatta a qualsiasi scopo particolare. Gli utenti sono tenuti a valutare autonomamente la ragionevolezza e l’affidabilità dei risultati della simulazione della Piattaforma ed è severamente vietato applicare tali risultati a transazioni finanziarie reali, decisioni di investimento, pianificazione finanziaria o qualsiasi altro contesto giuridicamente vincolante.' },
    { h: '5. Obblighi degli Utenti e Restrizioni di Utilizzo', p: 'Gli utenti accettano di rispettare rigorosamente i seguenti obblighi: 1. Non utilizzare la Piattaforma per qualsiasi attività che violi le leggi e i regolamenti applicabili, le convenzioni internazionali o l’ordine pubblico e il buon costume; 2. Non utilizzare la Piattaforma per transazioni in denaro reale, riciclaggio di denaro, frode, raccolta illegale di fondi o altre attività finanziarie illecite; 3. Non sottoporre a ingegneria inversa, decompilare, craccare o impiegare qualsiasi mezzo tecnico per ottenere il codice sorgente o la logica centrale della Piattaforma; 4. Non utilizzare la Piattaforma, o qualsiasi parte di essa (inclusi design dell’interfaccia, codice, dati simulati e contenuti testuali), per scopi commerciali, inclusi ma non limitati a vendita, locazione, concessione di licenze, incorporamento di pubblicità o raggruppamento; 5. Non trasmettere o diffondere alcun software dannoso, virus, cavalli di Troia o altri codici dannosi attraverso la Piattaforma; 6. Segnalare tempestivamente eventuali vulnerabilità di sicurezza o anomalie funzionali attraverso i canali designati, senza sfruttare o divulgare pubblicamente tali informazioni in modo dannoso; 7. Assumersi la piena responsabilità legale per tutte le azioni eseguite sulla Piattaforma.' },
    { h: '6. Legge Applicabile e Risoluzione delle Controversie', p: 'La presente Dichiarazione di Esclusione di Responsabilità, insieme all’uso, all’interpretazione, alla validità, all’esecuzione e alla risoluzione delle controversie relative alla Piattaforma, è regolata e interpretata in conformità con le leggi della Repubblica Italiana, escludendo le sue norme sul conflitto di leggi. Qualsiasi controversia derivante o relativa alla Piattaforma deve essere prima sottoposta a negoziazione amichevole tra le parti. In caso di fallimento della negoziazione, ciascuna parte ha il diritto di sottoporre la controversia al tribunale competente avente giurisdizione sul luogo di residenza dello sviluppatore per il contenzioso. Gli utenti riconoscono e accettano espressamente che la suddetta clausola di risoluzione delle controversie non può essere modificata dalle disposizioni legali del paese o della regione di residenza dell’utente.' },
    { h: '7. Riconoscimento dell’Utente', p: 'Accedendo o utilizzando la Piattaforma per la prima volta, gli utenti sono considerati avere letto, compreso e accettato incondizionatamente tutti i termini della presente Dichiarazione. Se un utente non accetta alcuna parte della presente Dichiarazione, deve cessare immediatamente l’uso della Piattaforma e chiudere la pagina pertinente. La Piattaforma si riserva il diritto di rivedere la presente Dichiarazione in qualsiasi momento, con la versione rivista che sarà pubblicata su questa pagina ed efficace a partire dalla data di pubblicazione. Gli utenti sono obbligati a rivedere periodicamente gli aggiornamenti e l’uso continuato della Piattaforma costituirà accettazione di tutti i termini rivisti.' },
  ],
  'de': [
    { h: '1. Art der Plattform', p: 'Diese Website (nachfolgend als die "Plattform" bezeichnet) ist ein pädagogisches Finanzsimulationstool, das eine virtuelle Umgebung für Finanzoperationen bieten soll. Die Plattform erbringt keinerlei reale Finanzdienstleistungen, einschließlich, aber nicht beschränkt auf, Verwahrung von Geldern, Geldtransfers, Zahlungen, Anlageverwaltung oder Kreditbewertung. Alle auf der Plattform angezeigten Transaktionsaufzeichnungen, Kontostände, Vermögensschwankungen und Ertragsdaten werden ausschließlich zu Demonstrationszwecken simuliert und generiert. Solche Daten stellen keine realen Finanzinformationen dar und besitzen keine rechtliche Gültigkeit. Es ist den Benutzern streng untersagt, Inhalte der Plattform für finanzielle Entscheidungen in der realen Welt oder als Grundlage für Investitionen zu verwenden.' },
    { h: '2. Geistiges Eigentum und Marken', p: 'Die auf der Benutzeroberfläche der Plattform angezeigten Kreditkartendesigns, Logos von Zahlungsinstituten (einschließlich, aber nicht beschränkt auf, Visa, Mastercard, American Express usw.), Namen von Finanzinstituten und Embleme sind eingetragene Marken oder kommerzielle Kennzeichen ihrer jeweiligen Eigentümer. Die Plattform verweist auf die vorgenannten Marken ausschließlich zum Zweck der Simulation realistischer Nutzungsszenarien und zur Verbesserung der visuellen Benutzererfahrung. Die Plattform steht in keinerlei Zusammenarbeit, Sponsoring, Autorisierung oder Verbindung mit den vorgenannten Markeninhabern. Die Plattform erhebt keinerlei Rechte an den vorgenannten Marken. Benutzer dürfen keine Inhalte der Plattform als offizielles Produkt eines tatsächlichen Finanzinstituts missverstehen. Die unbefugte Nutzung der vorgenannten Marken kann eine Rechtsverletzung darstellen, und die Benutzer tragen die entsprechende rechtliche Verantwortung.' },
    { h: '3. Daten und Datenschutz', p: 'Während des Betriebs der Plattform können Benutzeraktivitätsdaten (wie simulierte Transaktionsprotokolle und Kontoeinstellungen) aufgezeichnet werden. Solche Daten werden ausschließlich auf dem lokalen Gerät des Benutzers oder in dem vom Benutzer festgelegten Cloud-Speicher gespeichert. Der Plattformentwickler sammelt, lädt, analysiert oder überträgt die persönlichen Daten der Benutzer nicht aktiv an Dritte. Die Benutzer sind allein für die Sicherheit ihrer Datenspeicherung verantwortlich. Die Plattform beinhaltet nicht die Erhebung sensibler persönlicher Informationen, einschließlich, aber nicht beschränkt auf, reale Namen, nationale Identifikationsnummern, Bankkartendetails oder biometrische Daten. Sofern in die Plattform eingebettete Dienste Dritter die Übertragung von Benutzerinformationen betreffen, sollten die Benutzer die Datenschutzrichtlinien dieser Dienste sorgfältig lesen, und die Plattform übernimmt keine Verantwortung für die Datenschutzpraktiken von Drittanbietern.' },
    { h: '4. Haftungsbeschränkung und Gewährleistungsausschluss', p: 'Der Plattformentwickler übernimmt keinerlei Haftung für Schäden jeglicher Art, die aus Plattformstörungen, Softwarefehlern, Ungenauigkeiten in der Simulationsdaten, Netzwerkunterbrechungen, Anomalien von Drittanbieterdiensten oder anderen Ursachen entstehen, einschließlich, aber nicht beschränkt auf, Zeitverlust, Verlust von Gelegenheiten, Datenverlust, Enttäuschung über Leistungen oder Ergebnisse oder Verlust von Geschäftsmöglichkeiten. Die Plattform wird "wie besehen" und "wie verfügbar" zur Verfügung gestellt. Der Entwickler garantiert nicht, dass die Plattform fehlerfrei, unterbrechungsfrei, vollständig genau oder für einen bestimmten Zweck geeignet ist. Die Benutzer sind verpflichtet, die Angemessenheit und Zuverlässigkeit der Simulationsergebnisse der Plattform eigenständig zu beurteilen, und es ist ihnen streng untersagt, solche Ergebnisse auf reale Finanztransaktionen, Anlageentscheidungen, Finanzplanung oder andere rechtsverbindliche Zusammenhänge anzuwenden.' },
    { h: '5. Benutzerpflichten und Nutzungsbeschränkungen', p: 'Die Benutzer erklären sich damit einverstanden, die folgenden Pflichten strikt einzuhalten: 1. Die Plattform nicht für Aktivitäten zu nutzen, die gegen geltende Gesetze und Vorschriften, internationale Konventionen oder die öffentliche Ordnung und guten Sitten verstoßen; 2. Die Plattform nicht für reale Geldtransaktionen, Geldwäsche, Betrug, illegale Kapitalbeschaffung oder andere illegale Finanzaktivitäten zu verwenden; 3. Keine Rückentwicklung, Dekompilierung, kein Knacken oder Einsatz technischer Mittel, um den Quellcode oder die Kernlogik der Plattform zu erlangen; 4. Die Plattform oder Teile davon (einschließlich Schnittstellendesigns, Code, simulierte Daten und Textinhalte) nicht für kommerzielle Zwecke zu nutzen, einschließlich, aber nicht beschränkt auf, Verkauf, Vermietung, Lizenzierung, Einbettung von Werbung oder Bündelung; 5. Keine schädliche Software, Viren, Trojaner oder anderen schädlichen Code über die Plattform zu verbreiten; 6. Sicherheitslücken oder Funktionsanomalien unverzüglich über die dafür vorgesehenen Kanäle zu melden und solche Informationen nicht bösartig auszunutzen oder öffentlich zu verbreiten; 7. Die volle rechtliche Verantwortung für alle auf der Plattform durchgeführten Handlungen zu übernehmen.' },
    { h: '6. Anwendbares Recht und Streitbeilegung', p: 'Dieser Haftungsausschluss sowie die Nutzung, Auslegung, Gültigkeit, Durchführung und Streitbeilegung der Plattform unterliegen und werden ausgelegt nach dem Recht der Bundesrepublik Deutschland, unter Ausschluss seiner Kollisionsnormen. Streitigkeiten, die sich aus oder im Zusammenhang mit der Plattform ergeben, sind zunächst einer gütlichen Einigung zwischen den Parteien zu unterziehen. Im Falle des Scheiterns einer solchen Einigung hat jede Partei das Recht, die Streitigkeit dem zuständigen Gericht mit Gerichtsbarkeit über den Wohnsitz des Entwicklers zur Entscheidung vorzulegen. Die Benutzer erkennen ausdrücklich an und stimmen zu, dass die vorstehende Streitbeilegungsklausel nicht durch die gesetzlichen Bestimmungen des Landes oder der Region des Benutzers geändert werden darf.' },
    { h: '7. Bestätigung des Benutzers', p: 'Durch den erstmaligen Zugriff auf oder die Nutzung der Plattform gelten die Benutzer als alle in diesem Haftungsausschluss festgelegten Bedingungen gelesen, verstanden und bedingungslos akzeptiert zu haben. Wenn ein Benutzer nicht mit einem Teil dieses Haftungsausschlusses einverstanden ist, hat er die Nutzung der Plattform unverzüglich einzustellen und die betreffende Seite zu schließen. Die Plattform behält sich das Recht vor, diesen Haftungsausschluss jederzeit zu überarbeiten, wobei die überarbeitete Version auf dieser Seite veröffentlicht wird und mit dem Datum der Veröffentlichung in Kraft tritt. Die Benutzer sind verpflichtet, regelmäßig Aktualisierungen zu prüfen, und die fortgesetzte Nutzung der Plattform stellt die Annahme aller überarbeiteten Bedingungen dar.' },
  ],
  'fr': [
    { h: '1. Nature de la Plateforme', p: 'Le présent site web (ci-après dénommé la "Plateforme") est un outil pédagogique de simulation financière conçu pour offrir un environnement virtuel d’expériences opérationnelles financières. La Plateforme ne fournit aucun service financier réel, y compris, mais sans s’y limiter, la garde de fonds, les transferts d’argent, les paiements, la gestion d’investissements ou l’évaluation de crédit. Tous les enregistrements de transactions, soldes de comptes, fluctuations d’actifs et données de rendement affichés sur la Plateforme sont générés par simulation à des fins exclusivement démonstratives. Ces données ne constituent pas des informations financières réelles et n’ont aucune validité juridique. Il est strictement interdit aux utilisateurs d’utiliser tout contenu de la Plateforme pour des décisions financières réelles ou comme base d’investissement.' },
    { h: '2. Propriété Intellectuelle et Marques', p: 'Les modèles de cartes de crédit, les logos d’institutions de paiement (y compris, mais sans s’y limiter, Visa, Mastercard, American Express, etc.), les noms d’institutions financières et les emblèmes affichés sur l’interface de la Plateforme sont des marques déposées ou des identifiants commerciaux de leurs propriétaires respectifs. La Plateforme fait référence aux marques susmentionnées uniquement dans le but de simuler des scénarios d’utilisation réalistes et d’améliorer l’expérience visuelle de l’utilisateur. La Plateforme n’a aucune coopération, parrainage, autorisation ou affiliation avec les propriétaires des marques susmentionnées. La Plateforme ne revendique aucun droit sur les marques susmentionnées. Les utilisateurs ne doivent pas interpréter le contenu de la Plateforme comme un produit officiel d’une institution financière réelle. L’utilisation non autorisée des marques susmentionnées peut constituer une contrefaçon et les utilisateurs en assument la responsabilité légale correspondante.' },
    { h: '3. Données et Vie Privée', p: 'Lors du fonctionnement de la Plateforme, des données d’activité des utilisateurs (telles que les enregistrements de transactions simulées et les paramètres de compte) peuvent être enregistrées. Ces données sont stockées exclusivement sur l’appareil local de l’utilisateur ou dans le stockage cloud désigné par l’utilisateur. Le développeur de la Plateforme ne collecte, ne téléverse, n’analyse ni ne transmet activement les données personnelles des utilisateurs à des tiers. Les utilisateurs sont seuls responsables de la sécurité de leur stockage de données. La Plateforme n’implique pas la collecte d’informations personnelles sensibles, y compris, mais sans s’y limiter, les noms réels, les numéros d’identification nationaux, les coordonnées bancaires ou les données biométriques. Lorsque des services tiers intégrés à la Plateforme impliquent la transmission d’informations des utilisateurs, les utilisateurs sont invités à lire attentivement les politiques de confidentialité de ces services, et la Plateforme n’assume aucune responsabilité pour les pratiques de protection de la vie privée des services tiers.' },
    { h: '4. Limitation de Responsabilité et Clause de Non-Garantie', p: 'Le développeur de la Plateforme n’assume aucune responsabilité pour les dommages de quelque nature que ce soit résultant de dysfonctionnements de la plateforme, d’erreurs logicielles, d’inexactitudes dans les données de simulation, d’interruptions de réseau, d’anomalies de services tiers ou de toute autre cause, y compris, mais sans s’y limiter, la perte de temps, la perte d’opportunités, la perte de données, la déception quant aux performances ou aux résultats, ou la perte d’opportunités commerciales. La Plateforme est fournie "en l’état" et "dans la mesure de sa disponibilité". Le développeur ne garantit pas que la Plateforme est exempte d’erreurs, ininterrompue, entièrement exacte ou adaptée à un usage particulier. Les utilisateurs sont tenus d’évaluer de manière indépendante le caractère raisonnable et la fiabilité des résultats de simulation de la Plateforme, et il est strictement interdit d’appliquer ces résultats à des transactions financières réelles, des décisions d’investissement, une planification financière ou tout autre contexte juridiquement contraignant.' },
    { h: '5. Obligations des Utilisateurs et Restrictions d’Utilisation', p: 'Les utilisateurs acceptent de se conformer strictement aux obligations suivantes : 1. Ne pas utiliser la Plateforme pour toute activité qui viole les lois et règlements applicables, les conventions internationales ou l’ordre public et les bonnes mœurs ; 2. Ne pas utiliser la Plateforme pour des transactions monétaires réelles, le blanchiment d’argent, la fraude, la collecte illégale de fonds ou d’autres activités financières illicites ; 3. Ne pas procéder à une ingénierie inverse, une décompilation, un craquage ou utiliser tout moyen technique pour obtenir le code source ou la logique centrale de la Plateforme ; 4. Ne pas utiliser la Plateforme, ou toute partie de celle-ci (y compris les conceptions d’interface, le code, les données simulées et les contenus textuels), à des fins commerciales, y compris, mais sans s’y limiter, la vente, la location, la concession de licences, l’incorporation de publicité ou le groupement ; 5. Ne pas transmettre ou diffuser de logiciels malveillants, de virus, de chevaux de Troie ou d’autres codes nuisibles par l’intermédiaire de la Plateforme ; 6. Signaler rapidement toute vulnérabilité de sécurité ou anomalie fonctionnelle par les canaux désignés, sans exploiter ni divulguer publiquement ces informations de manière malveillante ; 7. Assumer l’entière responsabilité légale de toutes les actions effectuées sur la Plateforme.' },
    { h: '6. Droit Applicable et Résolution des Litiges', p: 'La présente Clause de Non-Responsabilité, ainsi que l’utilisation, l’interprétation, la validité, l’exécution et le règlement des litiges relatifs à la Plateforme, sont régis et interprétés conformément aux lois de la République française, à l’exclusion de ses règles de conflit de lois. Tout litige découlant de ou lié à la Plateforme doit être d’abord soumis à une négociation amiable entre les parties. En cas d’échec de la négociation, chaque partie a le droit de soumettre le litige au tribunal compétent ayant juridiction sur le lieu de résidence du développeur pour règlement contentieux. Les utilisateurs reconnaissent et acceptent expressément que la clause de résolution des litiges susmentionnée ne peut être modifiée par les dispositions légales du pays ou de la région de résidence de l’utilisateur.' },
    { h: '7. Acceptation par l’Utilisateur', p: 'En accédant ou en utilisant la Plateforme pour la première fois, les utilisateurs sont réputés avoir lu, compris et accepté sans condition toutes les dispositions de la présente Clause de Non-Responsabilité. Si un utilisateur n’accepte pas une partie quelconque de la présente Clause, il doit cesser immédiatement d’utiliser la Plateforme et fermer la page concernée. La Plateforme se réserve le droit de réviser la présente Clause à tout moment, la version révisée étant publiée sur cette page et prenant effet à compter de la date de publication. Les utilisateurs sont tenus de consulter périodiquement les mises à jour, et l’utilisation continue de la Plateforme constitue l’acceptation de toutes les conditions révisées.' },
  ],
};
